apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dhalls.softwarefactory-project.io
spec:
  group: softwarefactory-project.io
  names:
    kind: Dhall
    listKind: DhallList
    plural: dhalls
    singular: dhall
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
